const { translateMessage } = require("./44352");

("use strict");

const translations = {
  Close_input: "Close",
  Back_input: "Back",
  Minimize_input: "Minimize",
  "Hull MA_input": "Hull MA",
  "{number} item_combobox_input": "{number} item",
  Length_input: "Length",
  Plot_input: "Plot",
  Zero_input: "Zero",
  Signal_input: "Signal",
  Long_input: "Long",
  Short_input: "Short",
  UpperLimit_input: "UpperLimit",
  LowerLimit_input: "LowerLimit",
  Offset_input: "Offset",
  length_input: "length",
  mult_input: "mult",
  short_input: "short",
  long_input: "long",
  Limit_input: "Limit",
  Move_input: "Move",
  Value_input: "Value",
  Method_input: "Method",
  "Values in status line_input": "Values in status line",
  "Labels on price scale_input": "Labels on price scale",
  "Accumulation/Distribution_input": "Accumulation/Distribution",
  ADR_B_input: "ADR_B",
  "Equality Line_input": "Equality Line",
  "Window Size_input": "Window Size",
  Sigma_input: "Sigma",
  "Aroon Up_input": "Aroon Up",
  "Aroon Down_input": "Aroon Down",
  Upper_input: "Upper",
  Lower_input: "Lower",
  Deviation_input: "Deviation",
  "Levels Format_input": "Levels Format",
  "Labels Position_input": "Labels Position",
  "0 Level Color_input": "0 Level Color",
  "0.236 Level Color_input": "0.236 Level Color",
  "0.382 Level Color_input": "0.382 Level Color",
  "0.5 Level Color_input": "0.5 Level Color",
  "0.618 Level Color_input": "0.618 Level Color",
  "0.65 Level Color_input": "0.65 Level Color",
  "0.786 Level Color_input": "0.786 Level Color",
  "1 Level Color_input": "1 Level Color",
  "1.272 Level Color_input": "1.272 Level Color",
  "1.414 Level Color_input": "1.414 Level Color",
  "1.618 Level Color_input": "1.618 Level Color",
  "1.65 Level Color_input": "1.65 Level Color",
  "2.618 Level Color_input": "2.618 Level Color",
  "2.65 Level Color_input": "2.65 Level Color",
  "3.618 Level Color_input": "3.618 Level Color",
  "3.65 Level Color_input": "3.65 Level Color",
  "4.236 Level Color_input": "4.236 Level Color",
  "-0.236 Level Color_input": "-0.236 Level Color",
  "-0.382 Level Color_input": "-0.382 Level Color",
  "-0.618 Level Color_input": "-0.618 Level Color",
  "-0.65 Level Color_input": "-0.65 Level Color",
  ADX_input: "ADX",
  "ADX Smoothing_input": "ADX Smoothing",
  "DI Length_input": "DI Length",
  Smoothing_input: "Smoothing",
  ATR_input: "ATR",
  Growing_input: "Growing",
  Falling_input: "Falling",
  "Color 0_input": "Color 0",
  "Color 1_input": "Color 1",
  Source_input: "Source",
  StdDev_input: "StdDev",
  Basis_input: "Basis",
  Median_input: "Median",
  "Bollinger Bands %B_input": "Bollinger Bands %B",
  Overbought_input: "Overbought",
  Oversold_input: "Oversold",
  "Bollinger Bands Width_input": "Bollinger Bands Width",
  "RSI Length_input": "RSI Length",
  "UpDown Length_input": "UpDown Length",
  "ROC Length_input": "ROC Length",
  MF_input: "MF",
  resolution_input: "resolution",
  "Fast Length_input": "Fast Length",
  "Slow Length_input": "Slow Length",
  "Chaikin Oscillator_input": "Chaikin Oscillator",
  P_input: "P",
  X_input: "X",
  Q_input: "Q",
  p_input: "p",
  x_input: "x",
  q_input: "q",
  Price_input: "Price",
  "Chande MO_input": "Chande MO",
  "Zero Line_input": "Zero Line",
  "Color 2_input": "Color 2",
  "Color 3_input": "Color 3",
  "Color 4_input": "Color 4",
  "Color 5_input": "Color 5",
  "Color 6_input": "Color 6",
  "Color 7_input": "Color 7",
  "Color 8_input": "Color 8",
  CHOP_input: "CHOP",
  "Upper Band_input": "Upper Band",
  "Lower Band_input": "Lower Band",
  CCI_input: "CCI",
  "Smoothing Line_input": "Smoothing Line",
  "Smoothing Length_input": "Smoothing Length",
  "WMA Length_input": "WMA Length",
  "Long RoC Length_input": "Long RoC Length",
  "Short RoC Length_input": "Short RoC Length",
  sym_input: "sym",
  Symbol_input: "Symbol",
  Correlation_input: "Correlation",
  Period_input: "Period",
  Centered_input: "Centered",
  "Detrended Price Oscillator_input": "Detrended Price Oscillator",
  isCentered_input: "isCentered",
  DPO_input: "DPO",
  "ADX smoothing_input": "ADX smoothing",
  "+DI_input": "+DI",
  "-DI_input": "-DI",
  DEMA_input: "DEMA",
  Divisor_input: "Divisor",
  EOM_input: "EOM",
  "Elder's Force Index_input": "Elder's Force Index",
  Percent_input: "Percent",
  Exponential_input: "Exponential",
  Average_input: "Average",
  "Upper Percentage_input": "Upper Percentage",
  "Lower Percentage_input": "Lower Percentage",
  Fisher_input: "Fisher",
  Trigger_input: "Trigger",
  Level_input: "Level",
  "Trader EMA 1 length_input": "Trader EMA 1 length",
  "Trader EMA 2 length_input": "Trader EMA 2 length",
  "Trader EMA 3 length_input": "Trader EMA 3 length",
  "Trader EMA 4 length_input": "Trader EMA 4 length",
  "Trader EMA 5 length_input": "Trader EMA 5 length",
  "Trader EMA 6 length_input": "Trader EMA 6 length",
  "Investor EMA 1 length_input": "Investor EMA 1 length",
  "Investor EMA 2 length_input": "Investor EMA 2 length",
  "Investor EMA 3 length_input": "Investor EMA 3 length",
  "Investor EMA 4 length_input": "Investor EMA 4 length",
  "Investor EMA 5 length_input": "Investor EMA 5 length",
  "Investor EMA 6 length_input": "Investor EMA 6 length",
  HV_input: "HV",
  "Conversion Line Periods_input": "Conversion Line Periods",
  "Base Line Periods_input": "Base Line Periods",
  "Lagging Span_input": "Lagging Span",
  "Conversion Line_input": "Conversion Line",
  "Base Line_input": "Base Line",
  "Leading Span A_input": "Leading Span A",
  "Leading Span B_input": "Leading Span B",
  "Plots Background_input": "Plots Background",
  "yay Color 0_input": "yay Color 0",
  "yay Color 1_input": "yay Color 1",
  Multiplier_input: "Multiplier",
  "Bands style_input": "Bands style",
  Middle_input: "Middle",
  useTrueRange_input: "useTrueRange",
  ROCLen1_input: "ROCLen1",
  ROCLen2_input: "ROCLen2",
  ROCLen3_input: "ROCLen3",
  ROCLen4_input: "ROCLen4",
  SMALen1_input: "SMALen1",
  SMALen2_input: "SMALen2",
  SMALen3_input: "SMALen3",
  SMALen4_input: "SMALen4",
  SigLen_input: "SigLen",
  KST_input: "KST",
  Sig_input: "Sig",
  roclen1_input: "roclen1",
  roclen2_input: "roclen2",
  roclen3_input: "roclen3",
  roclen4_input: "roclen4",
  smalen1_input: "smalen1",
  smalen2_input: "smalen2",
  smalen3_input: "smalen3",
  smalen4_input: "smalen4",
  siglen_input: "siglen",
  "Upper Deviation_input": "Upper Deviation",
  "Lower Deviation_input": "Lower Deviation",
  "Use Upper Deviation_input": "Use Upper Deviation",
  "Use Lower Deviation_input": "Use Lower Deviation",
  Count_input: "Count",
  Crosses_input: "Crosses",
  MOM_input: "MOM",
  MA_input: "MA",
  "Length EMA_input": "Length EMA",
  "Length MA_input": "Length MA",
  "Fast length_input": "Fast length",
  "Slow length_input": "Slow length",
  "Signal smoothing_input": "Signal smoothing",
  "Simple ma(oscillator)_input": "Simple ma(oscillator)",
  "Simple ma(signal line)_input": "Simple ma(signal line)",
  Histogram_input: "Histogram",
  MACD_input: "MACD",
  fastLength_input: "fastLength",
  slowLength_input: "slowLength",
  signalLength_input: "signalLength",
  NV_input: "NV",
  OnBalanceVolume_input: "OnBalanceVolume",
  Start_input: "Start",
  Increment_input: "Increment",
  "Max value_input": "Max value",
  ParabolicSAR_input: "ParabolicSAR",
  start_input: "start",
  increment_input: "increment",
  maximum_input: "maximum",
  "Short length_input": "Short length",
  "Long length_input": "Long length",
  OSC_input: "OSC",
  shortlen_input: "shortlen",
  longlen_input: "longlen",
  PVT_input: "PVT",
  ROC_input: "ROC",
  RSI_input: "RSI",
  RVGI_input: "RVGI",
  RVI_input: "RVI",
  "Long period_input": "Long period",
  "Short period_input": "Short period",
  "Signal line period_input": "Signal line period",
  SMI_input: "SMI",
  "SMI Ergodic Oscillator_input": "SMI Ergodic Oscillator",
  Indicator_input: "Indicator",
  Oscillator_input: "Oscillator",
  K_input: "K",
  D_input: "D",
  smoothK_input: "smoothK",
  smoothD_input: "smoothD",
  "%K_input": "%K",
  "%D_input": "%D",
  "Stochastic Length_input": "Stochastic Length",
  "RSI Source_input": "RSI Source",
  lengthRSI_input: "lengthRSI",
  lengthStoch_input: "lengthStoch",
  TRIX_input: "TRIX",
  TEMA_input: "TEMA",
  "Long Length_input": "Long Length",
  "Short Length_input": "Short Length",
  "Signal Length_input": "Signal Length",
  Length1_input: "Length1",
  Length2_input: "Length2",
  Length3_input: "Length3",
  length7_input: "length7",
  length14_input: "length14",
  length28_input: "length28",
  UO_input: "UO",
  VWMA_input: "VWMA",
  len_input: "len",
  "VI +_input": "VI +",
  "VI -_input": "VI -",
  "%R_input": "%R",
  "Jaw Length_input": "Jaw Length",
  "Teeth Length_input": "Teeth Length",
  "Lips Length_input": "Lips Length",
  Jaw_input: "Jaw",
  Teeth_input: "Teeth",
  Lips_input: "Lips",
  "Jaw Offset_input": "Jaw Offset",
  "Teeth Offset_input": "Teeth Offset",
  "Lips Offset_input": "Lips Offset",
  "Down fractals_input": "Down fractals",
  "Up fractals_input": "Up fractals",
  Periods_input: "Periods",
  Shapes_input: "Shapes",
  "show MA_input": "show MA",
  "MA Length_input": "MA Length",
  "Color based on previous close_input": "Color based on previous close",
  "Rows Layout_input": "Rows Layout",
  "Row Size_input": "Row Size",
  Volume_input: "Volume",
  "Value Area volume_input": "Value Area volume",
  "Extend Right_input": "Extend Right",
  "Extend POC Right_input": "Extend POC Right",
  "Extend VAH Right_input": "Extend VAH Right",
  "Extend VAL Right_input": "Extend VAL Right",
  "Value Area Volume_input": "Value Area Volume",
  Placement_input: "Placement",
  POC_input: "POC",
  "Developing Poc_input": "Developing Poc",
  "Up Volume_input": "Up Volume",
  "Down Volume_input": "Down Volume",
  "Value Area_input": "Value Area",
  "Histogram Box_input": "Histogram Box",
  "Value Area Up_input": "Value Area Up",
  "Value Area Down_input": "Value Area Down",
  "Number Of Rows_input": "Number Of Rows",
  "Ticks Per Row_input": "Ticks Per Row",
  "Up/Down_input": "Up/Down",
  Total_input: "Total",
  Delta_input: "Delta",
  Bar_input: "Bar",
  Day_input: "Day",
  "Deviation (%)_input": "Deviation (%)",
  Depth_input: "Depth",
  "Extend to last bar_input": "Extend to last bar",
  Simple_input: "Simple",
  Weighted_input: "Weighted",
  "Wilder's Smoothing_input": "Wilder's Smoothing",
  "1st Period_input": "1st Period",
  "2nd Period_input": "2nd Period",
  "3rd Period_input": "3rd Period",
  "4th Period_input": "4th Period",
  "5th Period_input": "5th Period",
  "6th Period_input": "6th Period",
  "Rate of Change Lookback_input": "Rate of Change Lookback",
  "Instrument 1_input": "Instrument 1",
  "Instrument 2_input": "Instrument 2",
  "Rolling Period_input": "Rolling Period",
  "Standard Errors_input": "Standard Errors",
  "Averaging Periods_input": "Averaging Periods",
  "Days Per Year_input": "Days Per Year",
  "Market Closed Percentage_input": "Market Closed Percentage",
  "ATR Mult_input": "ATR Mult",
  VWAP_input: "VWAP",
  "Anchor Period_input": "Anchor Period",
  Session_input: "Session",
  Week_input: "Week",
  Month_input: "Month",
  Year_input: "Year",
  Decade_input: "Decade",
  Century_input: "Century",
  Sessions_input: "Sessions",
  "Each (pre-market, market, post-market)_input":
    "Each (pre-market, market, post-market)",
  "Pre-market only_input": "Pre-market only",
  "Market only_input": "Market only",
  "Post-market only_input": "Post-market only",
  "Main chart symbol_input": "Main chart symbol",
  "Another symbol_input": "Another symbol",
  Line_input: "Line",
  "Nothing selected_combobox_input": "Nothing selected",
  "All items_combobox_input": "All items",
  Cancel_input: "Cancel",
  Open_input: "Open",
};

function getStudyInputsInfo(study) {
  if (typeof study.inputs === "undefined") {
    return [];
  }

  return study.inputs.map((input) => ({
    ...input,
    id: input.id,
    localizedName:
      typeof input.name !== "undefined"
        ? translateMessage(input.name, { context: "input" }, translations)
        : "",
  }));
}

module.exports = {
  getStudyInputsInfo,
};
