export const intervalsVisibilitiesDefaults = {
  ticks: true,
  seconds: true,
  secondsFrom: 1,
  secondsTo: 59,
  minutes: true,
  minutesFrom: 1,
  minutesTo: 59,
  hours: true,
  hoursFrom: 1,
  hoursTo: 24,
  days: true,
  daysFrom: 1,
  daysTo: 366,
  weeks: true,
  weeksFrom: 1,
  weeksTo: 52,
  months: true,
  monthsFrom: 1,
  monthsTo: 12,
  ranges: true,
};
